In [61]:
import numpy as np

temp = np.array([4,1,0,-2,5,7,-3,0,0,5,0,-1,3,6,9,5,7,11,9,6,0])

temp[temp < 0].size

3

In [62]:
np.argmax(temp)

17

In [74]:
print(np.any(temp > 10))
print(np.any(temp > 20))

True
False


In [64]:
np.all(temp < 10)

False

In [65]:
temp[temp < 0]

array([-2, -3, -1])

In [66]:
np.sort(temp)

array([-3, -2, -1,  0,  0,  0,  0,  0,  1,  3,  4,  5,  5,  5,  6,  6,  7,
        7,  9,  9, 11])

In [67]:
v1 = np.array([3, 7])
v2 = np.array([2, 2])
v1 + v2

array([5, 9])

In [68]:
v1 * 2

array([ 6, 14])

In [69]:
v1 - v2

array([1, 5])

In [70]:
np.dot(v1, v2)

20

In [71]:
np.linalg.norm(v1)

7.615773105863909

In [72]:
np.linalg.norm(v1 - v2)

5.0990195135927845

In [73]:
np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))

0.9284766908852592

In [75]:
v1.shape

(2,)

In [83]:
mtrx = np.array([[1,2,3],[4,5,6],[7,8,9]])
mtrx

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
mtrx[2,:]

array([7, 8, 9])

In [98]:
mtrx2 = np.array([2, 3, 4])

In [92]:
mtrx + mtrx2

array([[ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [93]:
np.dot(mtrx, mtrx2)

array([20, 47, 74])

In [99]:
mtrx.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [100]:
mtrx.T.T == mtrx

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [101]:
np.linalg.det(mtrx)

-9.51619735392994e-16

In [102]:
np.linalg.inv(mtrx)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [104]:
np.linalg.matrix_rank(mtrx)

2

In [109]:

a = np.array([[1,5],[2,3]])
b = np.array([11,8])
x = np.linalg.solve(a,b)
print(x)
print(np.dot(a, x))

[1. 2.]
[11.  8.]
